### ISSUE TITLE
Default Google Play Music Thumbnail source does not retrieve PNGs correctly

### ISSUE THREAD

**Issue by StephenGregory** [StephenGregory/google-music-desktop-wallpapers#8]
Stack traces:

```
TypeError: Cannot read property 'length' of null
index.js:150
    at new Jimp (/Users/stephen.gregory/gmusicHooks/node_modules/jimp/index.js:150:53)
```

```
/Users/stephen.gregory/gmusicHooks/node_modules/jimp/index.js:150
        var bitmap = new Buffer(original.bitmap.data.length);
                                                    ^
TypeError: Cannot read property 'length' of null
    at new Jimp (/Users/stephen.gregory/gmusicHooks/node_modules/jimp/index.js:150:53)
    at Jimp.clone (/Users/stephen.gregory/gmusicHooks/node_modules/jimp/index.js:541:17)
```

Not working:

- Best for  You Love - Bad Religion - The Dissent Of Man ( Bonus Track Version)

- Big Sky, MT - Said the Whale (png)
  - https://lh3.ggpht.com/67s8C5dL75_poFC_3n8zmRt4mZ3bnCl1wr0nAm6F8ypE9wlpLLbNeUi4D7dkktzrQG-KByBP=s180-c-e100

- The Island - Bad Religion (png)
  - https://lh3.googleusercontent.com/qO15mPXVzqB7excu5609LJM-J3luxMrNHq_R0V0uhaP8QvzfosfqP1W5DR3MlQXHHLu_7pW9=s180-c-e100

Working (for comparison):

- Step Into The Darkness - Said the Whale (jpeg)
  - https://lh3.googleusercontent.com/kL1Yu49wPcDmuPE3eWmCXdJJM4gszOXJ67u9knJ8_-E1vN-GhKTBmGsbMvMGp7wr7GEJBrcu=s180-c-e100

- Subterranean - Foo Fighters (jped)
  - https://lh5.ggpht.com/65bjhDSEIt3nJAn85nGsfx6yrPq7QTxOQqKQXnCUosbgY1JZrxoIrIAgvc9I9E6OmFnyk_sb=s180-c-e100

**Comment by StephenGregory** [comment]
Can no longer reproduce this.

**Comment by StephenGregory** [comment]
Ad Hominem - Bad Religion had issues today.

**Comment by StephenGregory** [comment]
Seems that doing

```Javascript

Jimp.read(imageBuffer).then((albumArt) => {

// create wallpaper

})
.catch((error) => log.error(err));
```

handles png buffers well.

What I am doing, (`new Jimp(imageBuffer, () => {})`) does not.
